app.config(function($stateProvider,$urlRouterProvider){
	$stateProvider.state("page_one",{
		url:"/page1",
		templateUrl:"template/page_one.html",
		controller:"page_one"
	})
	.state("page_one.child_one",{
		url:"child1",            
		templateUrl:"template/child_one.html",
		controller:"child_one"
	});
	$stateProvider.state("page_two",{
		url:"/page2",
		templateUrl:"template/page_two.html",
		controller:"page_two"
	})
	.state("page_two.child_two",{
		url:"/child2",
		templateUrl:"template/child_two.html",
		controller:"child_two"
	});
	$urlRouterProvider.otherwise("page_one");
});